### ISSUE TITLE
Please releasse the currenct mai witht he updated swift-argument-parser

### ISSUE THREAD

**Issue by biovolt** [richardpiazza/VectorPlus#4]
Dear @richardpiazza 

Thank you for your work on VectorPlus!!!

Please release the current version with the updated swift-argument-parser 
The released version is not supported with R.Swift because if swift-argument-parser  version conflicts

**Comment by richardpiazza** [comment]
@biovolt Glad you find VectorPlus useful. I just published version [0.4.0](https://github.com/richardpiazza/VectorPlus/releases/tag/0.4.0) with the latest version of Swift Argument Parser.
